spring.application.name=demo
spring.data.mongodb.uri=mongodb://localhost:27017/Chat
spring.data.mongodb.database=Chat
cors.allowed-origins=http://localhost:5173
jwt.secret=your_very_very_very_very_long_secret_key_here_make_it_at_least_256_bits

# Configure maximum file upload size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

# Google Cloud Storage Configuration
gcp.bucket.name=community_storage
gcp.project.id=nomadic-drummer-453911-p9
gcp.credentials.path=C:/Users/Dell/Downloads/service.json
